# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Ml',
            },
        ),
        migrations.RemoveField(
            model_name='car_data',
            name='id',
        ),
        migrations.AddField(
            model_name='car_data',
            name='DTC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='UUID',
            field=models.CharField(default=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='car_data',
            name='average_fuel',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='battery_v',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='coolant_Temp',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='data_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='date_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='engine_load',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='fuel_consump_thistime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='fuel_left',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='hard_accel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='hard_breaks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='hotcar_du',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='idle_duration',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='idle_fuel_consump',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='instant_fuel',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='max_rpm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='max_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='rpm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='throttle_position',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='time_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_data',
            name='time_start',
            field=models.IntegerField(null=True),
        ),
    ]
